# X-API-KEY config
rest-api-key:
  http:
    auth-token-header-name: X-API-KEY
    auth-token: fdasrv34atdzbt4zeex7y

# Using generated security password: 1841f2d5-365e-4dd5-8a98-d25eed1cfbc8
# This generated password is for development use only. Your security configuration must be updated before running your application in production.
#
# 위 경고는 spring security에서 user를 구성하지 않으면 자동으로 비밀번호를 생성해 준다는 경고이다.
spring:
  security:
    user:
      name: hello
      password: hello